version: '3'
services:
  mlr-legacy-db-test:
    build:
      context: .
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MLR_LEGACY_PASSWORD=${MLR_LEGACY_PASSWORD}
      - MLR_LEGACY_DATA_PASSWORD=${MLR_LEGACY_DATA_PASSWORD}
      - MLR_LEGACY_USER_PASSWORD=${MLR_LEGACY_USER_PASSWORD}
      - MLR_LIQUIBASE_VERSION=${MLR_LIQUIBASE_VERSION}
      - POSTGRES_JDBC_VERSION=${POSTGRES_JDBC_VERSION}
      - LIQUIBASE_HOME=${LIQUIBASE_HOME}   
    ports:
      - "5435:5432"
    container_name: mlr-legacy-db-test
    env_file:
        - docker-compose.env
