version: '3'
services:
  mlr_legacy_db:
    build:
      context: .
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MLR_LEGACY_PASSWORD=${MLR_LEGACY_PASSWORD}
      - MLR_LEGACY_DATA_PASSWORD=${MLR_LEGACY_DATA_PASSWORD}
      - MLR_LEGACY_USER_PASSWORD=${MLR_LEGACY_USER_PASSWORD}
    ports:
      - "5435:5432"
    container_name: mlr_legacy_db
